config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing_page'
  resources :enneagram_scores, :pages
  resources :checkouts, only: [:new, :create]
  resources :responses do
    collection do
      delete 'remove_all'
    end
  end
  get 'test' => 'responses#new'

  resources :questions
  devise_for :users
  resources :enneagram_numbers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/landing_page'

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :enneagram_number
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order("created_at")
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :enneagram_number_id, :number_multiplier)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  
    <%= form.text_field :question, placeholder:"Question", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :enneagram_number_id, placeholder:"Enneagram Number", class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.number_field :number_multiplier, placeholder:"Number Multiplier", class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>
<br/  >
<%= link_to 'Show', @question, class: 'btn btn-primary' %> 
<%= link_to 'Back', questions_path, class:"btn btn-primary" %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Question</th>
      <th scope="col">Enneagram number</th>
      <th scope="col">Number multiplier</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= question.enneagram_number_id %></td>
        <td><%= question.number_multiplier %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path, class:"btn btn-primary" %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Enneagram number:</strong>
  <%= @question.enneagram_number_id %>
</p>
<p>
  <strong>Number Multiplier:</strong>
  <%= @question.number_multiplier %>
</p>

<div>
  <%= link_to 'Edit', edit_question_path(@question) %> 
</div>
<div>
  <%= link_to 'Back', questions_path %>
</div>
<div>
  <%= link_to 'New Question', new_question_path %>
</div>