config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing_page'
  resources :enneagram_scores, :pages
  resources :checkouts, only: [:new, :create]
  resources :responses do
    collection do
      delete 'remove_all'
    end
  end
  get 'test' => 'responses#new'

  resources :questions
  devise_for :users
  resources :enneagram_numbers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/landing_page'

end

app/models/enneagram_score.rb
class EnneagramScore < ApplicationRecord
  belongs_to :user

  ## This method is faulty because it does not select for current user. But it's in the model, so I don't have access
  ## the current user. I'm keeping this method as reference
  def self.enneagram_score(enneagram_number)
    @responses = Response.where(question_id:(Question.where(enneagram_number_id:(enneagram_number)))  )
    @responses.map{|r| r.answer}.sum
  end

  def self.enneagram_max_score(enneagram_number)
    @max_value = 
              (Question.where(enneagram_number_id:enneagram_number, number_multiplier:1).count)*100 +
              (Question.where(enneagram_number_id:enneagram_number, number_multiplier:2).count)*200
  end

  def self.top_enneagram_score
    @top_score = @enneagram_scores.zip(@enneagram_divisor).map{|x,y| ((x/y.to_f)*100).floor(2) }
    @top_score.each_index.sort_by{|i| -array[i]}[0] + 1
  end
end

app/controllers/enneagram_scores_controller.rb
class EnneagramScoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_enneagram_score, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    @enneagram_scores =[]
    (1..9).each do |number|
      @enneagram_scores <<
          (Response.where(user_id:current_user, question_id:(Question.where(enneagram_number_id:number)))).map{|r| r.answer * r.question.number_multiplier}.sum
    end
    
    @enneagram_number_divisor =[]
    (1..9).each do |number|
      @enneagram_number_divisor << EnneagramScore.where(user_id:(Response.where(user_id:current_user))).enneagram_max_score(number)
    end
    
    @enneagram_percentages = @enneagram_scores.zip(@enneagram_number_divisor).map{|x,y| ((x/y.to_f)*100).floor(2) }
    
    my_type = @enneagram_percentages.each_index.sort_by{|i| -@enneagram_percentages[i]}[0] + 1
    @my_number = EnneagramNumber.where(id:my_type).first

    # @description = EnneagramNumber.where(id:@my_type).first.description
    # @core_need = EnneagramNumber.where(id:@my_type).first.core_need
    # @core_belief = EnneagramNumber.where(id:@my_type).first.core_belief
    # @core_pattern = EnneagramNumber.where(id:@my_type).first.core_pattern

    @sorted_enneagram_numbers = (@enneagram_percentages.each_index.sort_by{|x| -@enneagram_percentages[x]}).map{|x| x+1}
    @sorted_enneagram_percentages = (@enneagram_percentages.sort_by{|x| -x}).map{|x| x.round}

  end


  def new
    @enneagram_score = EnneagramScore.new
  end

  def create
    @enneagram_score = EnneagramScore.new(enneagram_score_params)
    @enneagram_score.user_id = current_user
    respond_to do |format|
      if @enneagram_score.save
        format.html { redirect_to @enneagram_score, notice: 'Enneagram score was successfully created.' }
        format.json { render :show, status: :created, location: @enneagram_score }
      else
        format.html { render :new }
        format.json { render json: @enneagram_score.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @enneagram_score.update(enneagram_score_params)
        format.html { redirect_to @enneagram_score, notice: 'Enneagram score was successfully updated.' }
        format.json { render :show, status: :ok, location: @enneagram_score }
      else
        format.html { render :edit }
        format.json { render json: @enneagram_score.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enneagram_score.destroy
    respond_to do |format|
      format.html { redirect_to enneagram_scores_url, notice: 'Enneagram score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enneagram_score
      @enneagram_score = EnneagramScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enneagram_score_params
      params.require(:enneagram_score).permit(:user_id, :enneagram_one_score, :enneagram_two_score, :enneagram_three_score, :enneagram_four_score, :enneagram_five_score, :enneagram_six_score, :enneagram_seven_score, :enneagram_eight_score, :enneagram_nine_score)
    end
end

app/helpers/enneagram_scores_helper.rb
module EnneagramScoresHelper
end

app/views/enneagram_scores/_form.html.erb
<%= form_with(model: enneagram_score, local: true) do |form| %>
  <% if enneagram_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enneagram_score.errors.count, "error") %> prohibited this enneagram_score from being saved:</h2>

      <ul>
        <% enneagram_score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :enneagram_one_score %>
    <%= form.number_field :enneagram_one_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_two_score %>
    <%= form.number_field :enneagram_two_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_three_score %>
    <%= form.number_field :enneagram_three_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_four_score %>
    <%= form.number_field :enneagram_four_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_five_score %>
    <%= form.number_field :enneagram_five_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_six_score %>
    <%= form.number_field :enneagram_six_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_seven_score %>
    <%= form.number_field :enneagram_seven_score %>
  </div>

  <div class="field">
    <%= form.label :enneagream_eight_score %>
    <%= form.number_field :enneagream_eight_score %>
  </div>

  <div class="field">
    <%= form.label :enneagram_nine_score %>
    <%= form.number_field :enneagram_nine_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enneagram_scores/edit.html.erb
<h1>Editing Enneagram Score</h1>

<%= render 'form', enneagram_score: @enneagram_score %>

<%= link_to 'Show', @enneagram_score %> |
<%= link_to 'Back', enneagram_scores_path %>

app/views/enneagram_scores/index.html.erb
<div class="font">
  <h1 class="text-center">Your Enneagram Type: <%= @my_type %> </h1>
  <h2 class="text-center">Type <%=@my_number.enneagram_number%></h2>
  <h3 class="text-center"><%=@my_number.description%></h3>

  <div class="grid">
    <div class="box">
      <h3 class="text-center title">How The Type Meets Needs</h3>
      <p class="text-center p-text"><%=@my_number.how_type_meets_needs%></p>
    </div>

    <div class="box">
      <h3 class="text-center title">Gifts</h3>
      <p class="text-center p-text"><%=@my_number.gifts%></p>
    </div>

  </div>
  <br>

  <h2>This is how your enneagram scores ranked</h2>
  <p class="p-text">The higher the bar, the more likely you match that particular Enneagram Type</p>
  
  <% @sorted_enneagram_percentages.zip(@sorted_enneagram_numbers).each do |enneagram_percent, enneagram_number| %>    
    <div class="personality-bar">
      <div class="enneagram-bar" style="width: <%=enneagram_percent%>%;">
        <h5>Type <%= enneagram_number %></h5>
        <!--<h4><%#= enneagram_percent %>%</h4>-->
      </div>
    </div>
  <% end %>




  <h2 class="text-center">Want to find out more?</h2>
  <h3 class="text-center">Head over to <a href="https://www.theartofgrowth.org/">TheArtOfGrowth.Org</a> </h3>
</div>

app/views/enneagram_scores/new.html.erb
<h1>New Enneagram Score</h1>

<%= render 'form', enneagram_score: @enneagram_score %>

<%= link_to 'Back', enneagram_scores_path %>

app/views/enneagram_scores/show.html.erb
<p>
  <strong>Enneagram one score:</strong>
  <%= @enneagram_score.enneagram_one_score %>
</p>

<p>
  <strong>Enneagram two score:</strong>
  <%= @enneagram_score.enneagram_two_score %>
</p>

<p>
  <strong>Enneagram three score:</strong>
  <%= @enneagram_score.enneagram_three_score %>
</p>

<p>
  <strong>Enneagram four score:</strong>
  <%= @enneagram_score.enneagram_four_score %>
</p>

<p>
  <strong>Enneagram five score:</strong>
  <%= @enneagram_score.enneagram_five_score %>
</p>

<p>
  <strong>Enneagram six score:</strong>
  <%= @enneagram_score.enneagram_six_score %>
</p>

<p>
  <strong>Enneagram seven score:</strong>
  <%= @enneagram_score.enneagram_seven_score %>
</p>

<p>
  <strong>Enneagream eight score:</strong>
  <%= @enneagram_score.enneagream_eight_score %>
</p>

<p>
  <strong>Enneagram nine score:</strong>
  <%= @enneagram_score.enneagram_nine_score %>
</p>

<%= link_to 'Edit', edit_enneagram_score_path(@enneagram_score) %> |
<%= link_to 'Back', enneagram_scores_path %>