config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing_page'
  resources :enneagram_scores, :pages
  resources :checkouts, only: [:new, :create]
  resources :responses do
    collection do
      delete 'remove_all'
    end
  end
  get 'test' => 'responses#new'

  resources :questions
  devise_for :users
  resources :enneagram_numbers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/landing_page'

end

app/models/enneagram_number.rb
class EnneagramNumber < ApplicationRecord
  has_many :questions
end

app/controllers/enneagram_numbers_controller.rb
class EnneagramNumbersController < ApplicationController
  before_action :set_enneagram_number, only: [:show, :edit, :update, :destroy]

  # GET /enneagram_numbers
  # GET /enneagram_numbers.json
  def index
    @enneagram_numbers = EnneagramNumber.all
  end

  # GET /enneagram_numbers/1
  # GET /enneagram_numbers/1.json
  def show
  end

  # GET /enneagram_numbers/new
  def new
    @enneagram_number = EnneagramNumber.new
  end

  # GET /enneagram_numbers/1/edit
  def edit
  end

  # POST /enneagram_numbers
  # POST /enneagram_numbers.json
  def create
    @enneagram_number = EnneagramNumber.new(enneagram_number_params)

    respond_to do |format|
      if @enneagram_number.save
        format.html { redirect_to @enneagram_number, notice: 'Enneagram number was successfully created.' }
        format.json { render :show, status: :created, location: @enneagram_number }
      else
        format.html { render :new }
        format.json { render json: @enneagram_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enneagram_numbers/1
  # PATCH/PUT /enneagram_numbers/1.json
  def update
    respond_to do |format|
      if @enneagram_number.update(enneagram_number_params)
        format.html { redirect_to @enneagram_number, notice: 'Enneagram number was successfully updated.' }
        format.json { render :show, status: :ok, location: @enneagram_number }
      else
        format.html { render :edit }
        format.json { render json: @enneagram_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enneagram_numbers/1
  # DELETE /enneagram_numbers/1.json
  def destroy
    @enneagram_number.destroy
    respond_to do |format|
      format.html { redirect_to enneagram_numbers_url, notice: 'Enneagram number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enneagram_number
      @enneagram_number = EnneagramNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enneagram_number_params
      params.require(:enneagram_number).permit(:enneagram_number,:description,:core_belief,:core_need,:core_pattern,:how_type_meets_needs,:gifts)
    end
end

app/helpers/enneagram_numbers_helper.rb
module EnneagramNumbersHelper
end

app/views/enneagram_numbers/_form.html.erb
<%= form_with(model: enneagram_number, local: true) do |form| %>
<% if enneagram_number.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(enneagram_number.errors.count, "error") %> prohibited this enneagram_number from being saved:</h2>

  <ul>
    <% enneagram_number.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :enneagram_number %>
  <%= form.number_field :enneagram_number %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>
<div class="field">
  <%= form.label :core_need %>
  <%= form.text_field :core_need %>
</div>

<div class="field">
  <%= form.label :how_type_meets_needs %>
  <%= form.text_area :how_type_meets_needs %>
</div>
<div class="field">
  <%= form.label :their_gifts %>
  <%= form.text_area :gifts %>
</div>


<div class="field">
  <%= form.label :core_belief %>
  <%= form.text_field :core_belief %>
</div>
<div class="field">
  <%= form.label :core_pattern %>
  <%= form.text_area :core_pattern %>
</div>


<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/enneagram_numbers/edit.html.erb
<h1>Editing Enneagram Number</h1>

<%= render 'form', enneagram_number: @enneagram_number %>

<%= link_to 'Show', @enneagram_number %> |
<%= link_to 'Back', enneagram_numbers_path %>

app/views/enneagram_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enneagram Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Enneagram number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enneagram_numbers.each do |enneagram_number| %>
      <tr>
        <td><%= enneagram_number.enneagram_number %></td>
        <td><%= link_to 'Show', enneagram_number %></td>
        <td><%= link_to 'Edit', edit_enneagram_number_path(enneagram_number) %></td>
        <td><%= link_to 'Destroy', enneagram_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enneagram Number', new_enneagram_number_path %>

app/views/enneagram_numbers/new.html.erb
<h1>New Enneagram Number</h1>

<%= render 'form', enneagram_number: @enneagram_number %>

<%= link_to 'Back', enneagram_numbers_path %>

app/views/enneagram_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Enneagram number:</strong>
  <%= @enneagram_number.enneagram_number %>
</p>
<p>
  <strong>Description:</strong>
  <%= @enneagram_number.description %>
</p>
<p>
  <strong>How the type meets their needs:</strong>
  <%= @enneagram_number.how_type_meets_needs %>
</p>
<p>
  <strong>Their Gifts:</strong>
  <%= @enneagram_number.gifts %>
</p>
<p>
  <strong>Core Belief:</strong>
  <%= @enneagram_number.core_belief %>
</p>
<p>
  <strong>Core Need:</strong>
  <%= @enneagram_number.core_need %>
</p>
<p>
  <strong>Core Pattern:</strong>
  <%= @enneagram_number.core_pattern %>
</p>

<%= link_to 'Edit', edit_enneagram_number_path(@enneagram_number) %> |
<%= link_to 'Back', enneagram_numbers_path %>