config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing_page'
  resources :enneagram_scores, :pages
  resources :checkouts, only: [:new, :create]
  resources :responses do
    collection do
      delete 'remove_all'
    end
  end
  get 'test' => 'responses#new'

  resources :questions
  devise_for :users
  resources :enneagram_numbers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/landing_page'

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end


  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @questions = Question.all.order(:created_at)
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    responses_saved = true
    params[:response].each do |response_param|
      @response = Response.new(response_param.permit(:user_id, :question_id, :answer))
      @response.user_id = current_user.id 
      unless @response.save
        responses_saved = false
        break
      end
    end
    
    respond_to do |format|
      if responses_saved
        format.html { redirect_to enneagram_scores_path, notice: 'Response was successfully created. Here are your results' }
        format.json { render :show, status: :created, location: @response }
        
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_all
    Response.delete_all
    flash[:notice] = "You have removed all results!"
    redirect_to root_path
  end

  private
   
    def set_response
      @response = Response.find(params[:id])
    end

    def response_params
      params.require(:response).permit(:user_id, :question_id, :answer).merge(user: current_user)
    end

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_enneagram_test.html.erb
<%# <h1 class="text-center">Enneagramtesting.org</h1> %>
<div class="enneagram-test remove-container">
  <%= form_with(model: response, local: true) do |form| %>
  <div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel" data-pause="hover" data-touch="false">
    <div class="row carousel-row align-items-center">
      <div class="col-md-12">

        <!-- questionair completeness indictor -->
        <ol class="carousel-indicators">
          <% @questions.each_with_index do |question, index| %>
          <li data-target="#carouselExampleControls" data-slide-to="<%=index%>" id="carousel-indicator"></li>
          <%end%>
        </ol>

        <div class="carousel-inner">
          <% @questions.each_with_index do |question, index| %>
          <div class="carousel-item text-center card">
            <%= fields_for "response[]", response do |response_field| %>
            <div class="card-head text-center">
              <h2 class="mt-4"><%=question.question %></h2>
              <%= response_field.hidden_field :question_id, value: question.id %>
              <%= response_field.hidden_field :user_id %>
            </div>
            <div class="card-body text-center">
              <p class="card-text">
                <%= response_field.label "How much does this describe you?"%>
              </p>
              <p class="percent-value">Value: <span id="question<%=index + 1%>score">50</span>%</p>
              <div class="row">
                <div class="col-2 px-0">
                  <p class="percent-text">0%</p>
                </div>
                <div class="col-8 remove-padding-left-right">
                  <%= response_field.range_field :answer, min:0, max:100, class:"slider-1", id:"question#{index+1}"%>
                </div>
                <div class="col-2 px-0">
                  <p class="percent-text">100%</p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>

    </div>
    <br>
    <div class="container">
      <div class="row scroll-arrows">
        <div class="col-md-6 arrow-button">
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
        </div>
        <div class="col-md-6 arrow-button">
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= form.submit "Show my type", class:"btn btn-primary", id:"calculate-btn"%>
  </div>
  <% end %>
</div>

app/views/responses/_form.html.erb
<%= form_with(model: response, local: true) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
        <% response.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer %>
    <%= form.number_field :answer %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th>Answer</th>
     
      <th>Question</th>
    
      <th>User</th>
     
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
    <tr>
      <td><%= response.answer %></td>
      <td><%= response.question_id %></td>
      <td><%= response.user_id %></td>
      <td><%= link_to 'Show', response %></td>
      <td><%= link_to 'Edit', edit_response_path(response) %></td>
      <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Remove All", remove_all_responses_path, :method => :delete %>
<br/>
<%= link_to 'Home', root_path %>

app/views/responses/new.html.erb
<%= render 'enneagram_test', response: @response %>

<%
=begin%>
 <%= link_to 'Back', responses_path %> 
<%
=end%>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @response.answer %>

  <strong>Question:</strong>
  <%= @response.question_id %>

  <strong>User:</strong>
  <%= @response.user_id %>
</p>
<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>